# Site settings
title: English Over Coffee
email: sheldon.j.johnson@outlook.com
url: http://drzel.github.com
description: "Casual, conversational English, over coffee."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 646464 #80B3FF
  secondary: 363942  #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Sheldon J. Johnson
  location: Two locations
  social: Around the Web
  credits: The man himself

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/drzel

# Postal address (add as many lines as necessary)
address:
  - line: "cafe The SUN LIVES HERE: 〒154-0024 東京都東京都世田谷区 三軒茶屋1-27-33"
  - line: ""
  - line: "JamHouse 天照: 〒154-0012 東京都世田谷区駒沢２丁目３３−７ 日本"
  
# Credits content
credits: "Sheldon J. Johnson is a Tokyo based English teacher, web developer, musician, conversationalist and avid chess player. He drinks his coffee black."

# Build settings
markdown: kramdown
permalink: none
  